# Generated by hand for adding display_name to CustomUser
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=150, blank=True, help_text='Public display name shown in chats and search'),
        ),
    ]
