# Generated by Django 5.2.6 on 2025-09-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pin_and_trusted_devices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='accounts_tr_user_id_87a2de_idx',
            old_name='accounts_tr_user_id_5f1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='accounts_tr_user_id_761002_idx',
            old_name='accounts_tr_user_id_1c9b4a_idx',
        ),
    ]
