# Generated by Django 5.2.6 on 2025-10-02 16:19

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pin_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.CharField(default=accounts.models._generate_device_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('primary', 'Primary'), ('active', 'Active'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('push_token', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('pending_token', models.CharField(blank=True, max_length=96)),
                ('pending_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_us_user_id_27865b_idx'), models.Index(fields=['pending_token'], name='accounts_us_pending_28717a_idx'), models.Index(fields=['user', 'last_seen_at'], name='accounts_us_user_id_63c862_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'primary')), fields=('user',), name='unique_primary_device_per_user')],
            },
        ),
    ]
