# Generated by Django 5.2.6 on 2025-10-04 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_web',
            field=models.BooleanField(default=False, help_text='Whether this device represents a linked web/browser session'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_web'], name='accounts_us_user_id_81c0e1_idx'),
        ),
        migrations.AddField(
            model_name='webloginsession',
            name='approved_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_sessions', to='accounts.userdevice'),
        ),
        migrations.AddField(
            model_name='webloginsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_login_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webloginsession',
            index=models.Index(fields=['status', 'expires_at'], name='accounts_we_status_0fa484_idx'),
        ),
        migrations.AddIndex(
            model_name='webloginsession',
            index=models.Index(fields=['created_at'], name='accounts_we_created_c16264_idx'),
        ),
    ]
