# Generated by Django 5.2.6 on 2025-10-06 22:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_webloginsession_userdevice_is_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_icon', models.ImageField(blank=True, help_text='أيقونة الإشعارات (PNG فقط) - تظهر في شريط الحالة بجانب البطارية', null=True, upload_to='notification_icons/', validators=[accounts.models.validate_png_only])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
