# Generated by Django 5.2.6 on 2025-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Hardware fingerprint - identifies physical device across browsers', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='stored_device_id',
            field=models.CharField(blank=True, help_text='Device ID from localStorage (secondary identifier)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='webloginsession',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Hardware fingerprint from browser', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='webloginsession',
            name='stored_device_id',
            field=models.CharField(blank=True, help_text='Device ID from localStorage (if available)', max_length=128, null=True),
        ),
    ]
