# Generated by Django 5.2.6 on 2025-09-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_message_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationInbox',
            fields=[
            ],
            options={
                'verbose_name': 'Admin inbox',
                'verbose_name_plural': 'Admin inbox',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.conversation',),
        ),
    ]
