# Generated by Django 5.2.6 on 2025-09-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_team_and_conversation_members'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationmember',
            new_name='communicati_convers_d93699_idx',
            old_name='comm_conv_member_idx',
        ),
        migrations.RenameIndex(
            model_name='teammember',
            new_name='communicati_owner_i_22c4db_idx',
            old_name='comm_team_owner_member_idx',
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
