# Generated by Django 5.2.6 on 2025-09-21 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_rename_comm_conv_member_idx_communicati_convers_d93699_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationmember',
            name='communicati_convers_d93699_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='communicati_owner_i_22c4db_idx',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='member_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_team_memberships', to='communications.teammember'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='member_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='communications.teammember'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='password_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'member_user'], name='communicati_convers_5acf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'member_team'], name='communicati_convers_3e5cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['owner', 'username'], name='communicati_owner_i_43dc5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member_user__isnull', False), ('member_team__isnull', True)), models.Q(('member_user__isnull', True), ('member_team__isnull', False)), _connector='OR'), name='conv_member_exactly_one'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('owner', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'member_team'), ('conversation', 'member_user')},
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
    ]
