# Generated by Django 5.2.6 on 2025-09-24 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_collapse_status_zero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delivery_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ConversationReadMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_markers', to='communications.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_read_markers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'user'], name='communicati_convers_cc01ee_idx'), models.Index(fields=['conversation', 'last_read_message_id'], name='communicati_convers_a331d6_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
