# Generated by Django 5.2.6 on 2025-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0018_brandingsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('email', 'Email')], max_length=32)),
                ('label', models.CharField(blank=True, help_text='النص الظاهر بجانب الأيقونة (اختياري)', max_length=100)),
                ('value', models.CharField(help_text='الرابط أو رقم التواصل (مثال: https://example.com أو tel:+963...)', max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رابط تواصل',
                'verbose_name_plural': 'روابط تواصل',
                'ordering': ['display_order', '-updated_at'],
            },
        ),
    ]
