# Generated by Django 5.2.6 on 2025-09-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0019_contactlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='النص الكامل لسياسة الخصوصية أو شروط الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='رتب السياسات، الأصغر يظهر أولاً')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سياسة خصوصية',
                'verbose_name_plural': 'سياسات الخصوصية',
                'ordering': ['display_order', '-updated_at'],
            },
        ),
    ]
