# Generated by Django 5.2.6 on 2025-09-28 01:02

from django.db import migrations, models


def assign_document_types(apps, schema_editor):
    PrivacyPolicy = apps.get_model('communications', 'PrivacyPolicy')
    for policy in PrivacyPolicy.objects.all():
        doc_type = 'privacy'
        try:
            title = (policy.title or '').strip().casefold()
        except Exception:
            title = ''
        try:
            content = (policy.content or '').strip().casefold()
        except Exception:
            content = ''
        haystack = f"{title} {content}"
        compact = haystack.replace(' ', '')
        keywords = ['terms', 'terms of use', 'شروط', 'استخدام']
        compact_keywords = ['termsofuse']
        if any(keyword in haystack for keyword in keywords) or any(keyword in compact for keyword in compact_keywords):
            doc_type = 'terms'
        if policy.document_type != doc_type:
            policy.document_type = doc_type
            policy.save(update_fields=['document_type'])


def revert_document_types(apps, schema_editor):
    PrivacyPolicy = apps.get_model('communications', 'PrivacyPolicy')
    PrivacyPolicy.objects.update(document_type='privacy')


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0020_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['document_type', 'display_order', '-updated_at'], 'verbose_name': 'مستند قانوني', 'verbose_name_plural': 'مستندات قانونية'},
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='document_type',
            field=models.CharField(choices=[('privacy', 'سياسة الخصوصية'), ('terms', 'شروط الاستخدام')], default='privacy', help_text='حدد ما إذا كان هذا المستند سياسة خصوصية أو شروط استخدام', max_length=20, verbose_name='نوع الوثيقة'),
        ),
        migrations.RunPython(assign_document_types, revert_document_types),
    ]
