# Generated by Django 5.2.6 on 2025-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0022_add_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=28),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_from',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_to',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=28, null=True),
        ),
    ]
