# Generated by Django 5.2.6 on 2025-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0023_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'client_id'], name='comm_msg_conv_client_idx'),
        ),
    ]
