# Generated by Django 5.2.6 on 2025-09-30 08:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


def link_transactions_to_messages(apps, schema_editor):
    Transaction = apps.get_model('communications', 'Transaction')
    Message = apps.get_model('communications', 'Message')
    used_message_ids = set(
        Transaction.objects.exclude(message__isnull=True).values_list('message_id', flat=True)
    )
    for txn in Transaction.objects.filter(message__isnull=True):
        prefix = f"معاملة: {'لنا' if txn.direction == 'lna' else 'لكم'}"
        candidates = Message.objects.filter(
            conversation_id=txn.conversation_id,
            sender_id=txn.from_user_id,
            type='transaction',
            body__startswith=prefix,
        ).order_by('created_at')
        chosen = None
        if txn.created_at:
            for candidate in candidates:
                if candidate.created_at:
                    delta = abs(candidate.created_at - txn.created_at)
                    if delta <= datetime.timedelta(minutes=5):
                        chosen = candidate
                        break
        if chosen is None:
            chosen = candidates.filter(created_at__gte=txn.created_at).first() if txn.created_at else None
        if chosen is None:
            chosen = candidates.first()
        if chosen and chosen.id not in used_message_ids:
            txn.message_id = chosen.id
            txn.save(update_fields=['message'])
            used_message_ids.add(chosen.id)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0024_message_client_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='communicati_convers_ac946e_idx',
            old_name='comm_msg_conv_client_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='communications.message'),
        ),
        migrations.RunPython(link_transactions_to_messages, migrations.RunPython.noop),
    ]
