# Generated by Django 5.2.6 on 2025-09-30 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0025_rename_comm_msg_conv_client_idx_communicati_convers_ac946e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConversationSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='communications.conversation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_events', to='communications.transaction')),
            ],
            options={
                'ordering': ['-settled_at', '-id'],
                'indexes': [models.Index(fields=['conversation', 'settled_at'], name='communicati_convers_14a5fb_idx')],
            },
        ),
    ]
