# Generated by Django 5.2.6 on 2025-10-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0028_loginpagesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpagesetting',
            name='qr_overlay_logo',
        ),
    ]
