# Generated by Django 5.2.6 on 2025-10-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0029_remove_loginpagesetting_qr_overlay_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationInbox',
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ['display_order', '-updated_at'], 'verbose_name': 'Contact Link', 'verbose_name_plural': 'Contact Links'},
        ),
        migrations.AlterModelOptions(
            name='logininstruction',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Login Instruction', 'verbose_name_plural': 'Login Instructions'},
        ),
        migrations.AlterModelOptions(
            name='loginpagesetting',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Login Page Setting', 'verbose_name_plural': 'Login Page Settings'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['document_type', 'display_order', '-updated_at'], 'verbose_name': 'Legal Document', 'verbose_name_plural': 'Legal Documents'},
        ),
    ]
