# Generated by Django 5.2.6 on 2025-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0030_delete_conversationinbox_alter_contactlink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='رمز الإيموجي (مثال: 😀 أو 🎉)', max_length=10, verbose_name='الإيموجي')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, help_text='إظهار هذا الإيموجي للمستخدمين', verbose_name='مفعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Emoji',
                'verbose_name_plural': 'Custom Emojis',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
