# Generated by Django 5.2.6 on 2025-09-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_trial_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('trial', 'Trial'), ('silver', 'Silver'), ('golden', 'Golden'), ('king', 'King')], max_length=20, unique=True),
        ),
    ]
