# Generated by Django 5.2.6 on 2025-09-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_trial_to_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('trial', 'مجاني'), ('silver', 'Silver'), ('golden', 'Golden'), ('king', 'King')], max_length=20, unique=True),
        ),
    ]
