# Generated by Django 5.2.6 on 2025-09-17 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_reduce_decimal_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(-999999999)]),
        ),
    ]
