# Generated by Django 5.2.6 on 2025-09-28 16:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('-99999999999999999999999'))]),
        ),
    ]
