# Generated by Django 5.2.6 on 2025-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'الأرباح',
                'verbose_name_plural': 'الأرباح',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'إحصائيات النظام',
                'verbose_name_plural': 'إحصائيات النظام',
                'managed': False,
            },
        ),
    ]
